spring:
  application:
    name: tinnova-challenge
  datasource:
    url: jdbc:h2:mem:veiculosdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs
